# Use an official OpenJDK runtime as a parent image
FROM openjdk:17

# Set the working directory inside the container
WORKDIR /app

# Copy the compiled Java class file into the container
COPY Main.class .

# Command to run the application
CMD ["java", "Main"]
